# Generated by Django 2.1.7 on 2026-02-14 09:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, help_text='Or enter image URL/path (e.g., images/articles/placeholder.svg)', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, help_text='Or enter image URL/path (e.g., images/articles/placeholder.svg)', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload article image', null=True, upload_to=core.models.article_image_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload category image', null=True, upload_to=core.models.category_image_path),
        ),
    ]
