# Generated by Django 2.1.7 on 2026-02-14 13:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260214_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to=core.models.profile_photo_path),
        ),
    ]
