# Generated by Django 2.1.7 on 2026-02-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0, help_text='Number of likes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_articles',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='core.Article'),
        ),
    ]
